Create Data SQL
IsmailChangezi/vet-clinic pull request #1
Opened 2023-05-09 12:32 UTC by IsmailChangezi

## Description 
- Install PSQL on my Computer.
- Create Database.
- Add tables to the data base 
- Add columns to database
- Perform queries on the items of the table.

### These are the snapshots of the queries.

![Screenshot 2023-05-09 172251](https://github.com/IsmailChangezi/vet-clinic/assets/96125730/73e42375-9455-42c7-84a2-1778dbb22157)

2023-05-09 12:40 UTC, iambenkis reviewed
Hi @IsmailChangezi  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that does not have a README file requested for microverse project , Kindly use the template provided by Microverse and customize it  😄 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-09 13:39 UTC, Gambit142 reviewed
Hi @IsmailChangezi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindy remove all placeholder texts from the README.md file. Also kindly remove the Live Demo Section from the README.md file since you would not be deploying the project. 👍 😎 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-09 14:00 UTC, BregornOriginal requested changes
Hi @IsmailChangezi  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![hand-sketching-stair-slogan-one-step-closer-chalkboard-79948193](https://github.com/IsmailChangezi/vet-clinic/assets/93630700/faa81e2f-36c5-495d-87f3-06a843197958)

## Highlights

✔️ Good work using the template provided 💯 
✔️ Linters are passing
✔️ Good commit history
✔️ Good Pull request description 🥇 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 14:00 UTC, BregornOriginal commented on schema.sql
> + id INT,
[OPTIONAL] Good work creating an animals table 💯 

[OPTIONAL] You could add to the `id` column, the following properties to help you while creating animals. 

`id int NOT NULL IDENTITY(1,1)`

2023-05-09 14:00 UTC, BregornOriginal commented on schema.sql
> + weight_kg DECIMAL);
[OPTIONAL] Good work creating an animals table 💯

[OPTIONAL] You could add to the animal's table, the following properties to help you while creating animals.

`PRIMARY KEY (id)`

2023-05-09 14:00 UTC, BregornOriginal commented on data.sql
> +INSERT INTO animals (id,name,date_of_birth,escape_attempts, neutered, weight_kg) VALUES (3, 'Pikachu', '2021-1-7',1,false,15.04 ), (4, 'Devimon', '2017-5-7', 5, true,11);
Good work creating animals! 💯 

As there's a lot of information that you need to enter manually, could happen that you have some typos. For example here, the animal `Devimon` has a different date that we have to input. 

- Kindly fix the date_of_birth of Devimon, the correct one is `2017/05/12`
- Kindly remember to use spaces before a `,` (coma) so your code will be more ordered and readable 🥇

2023-05-09 14:32 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @IsmailChangezi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- Good Summary
- Good PR Description

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 14:32 UTC, GedeonTS commented on data.sql
> +INSERT INTO animals (id,name,date_of_birth,escape_attempts, neutered, weight_kg) VALUES (3, 'Pikachu', '2021-1-7',1,false,15.04 ), (4, 'Devimon', '2017-5-7', 5, true,11);
- As Requested by your last reviewer [here](https://github.com/IsmailChangezi/vet-clinic/pull/1#discussion_r1188639486), Kindly make sure to put the correct birth date for Devimon, whose values are supposed to be `(4, 'Devimon', '2017-5-12', '5', 'true', '11');`

2023-05-11 12:16 UTC, ShadyShawkat approved these changes
## Hi @IsmailChangezi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 14:19 UTC, merged